FROM apache/spark:python3
USER root
WORKDIR /app
EXPOSE 4040
EXPOSE 15002
COPY analyzer.py .
COPY queries.py .
ENV PYTHONUNBUFFERED=1
RUN mkdir parquets
RUN mkdir parquets/events
RUN mkdir parquets/mentions
RUN mkdir parquets/gkg
RUN pip install pyarrow pandas pymongo pyspark
