services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017

  gdeltloader:
    container_name: gdeltloader
    build:
      context: .
      dockerfile: Dockerfile.loader
    volumes:
      - raw_data:/app/raw_jsons

  analyzer:
    container_name: analyzer
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    ports:
      - 4040:4040
      - 15002:15002
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
    command: >
      sh -c "
        /opt/spark/sbin/start-connect-server.sh --master local[*] &
        spark-submit --master local[*] analyzer.py"
    volumes:
      - raw_data:/app/raw_jsons
      - processed_data:/app/processed_jsons

  mongodbloader:
    container_name: mongodbloader
    build:
      context: .
      dockerfile: Dockerfile.database
    volumes:
      - processed_data:/app/processed_jsons

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 5000:5000
    depends_on:
      - mongodb

volumes:
  raw_data:
  processed_data:
  