services:
  loader:
    container_name: loader
    build:
      context: .
      dockerfile: Dockerfile.loader
    volumes:
      - volume:/app/shared

  analyzer:
    container_name: analyzer
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    ports:
      - 4040:4040
      - 15002:15002
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
    command:
      - sh
      - -c
      - |
        /opt/spark/sbin/start-connect-server.sh --master local[*]
    volumes:
      - volume:/app/shared

  mongodb:
    container_name: mongodb
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    ports: 
      - 27017:27017

  #frontend:
  #  container_name: frontend
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.frontend
volumes:
  volume:
  