FROM python:latest
USER root
WORKDIR /app
ENV PYTHONUNBUFFERED=1
RUN pip install flask pymongo
COPY frontend.py .
COPY templates ./templates
COPY static ./static
EXPOSE 5000
CMD ["python", "-u", "frontend.py"]
